-- ScamBomb Trivia Event
-- Run this in Supabase SQL Editor after schema.sql
-- Safe to re-run: deletes existing SCAMBOMB-TRIVIA event first

begin;

delete from events
where code = 'TRIVIA';

with new_event as (
  insert into events (code, active_question_id)
  values ('TRIVIA', null)
  returning id
)
insert into questions (event_id, prompt, options, sort_order, revealed, answer_revealed, correct_answer, explanation)
select
  new_event.id,
  payload.prompt,
  payload.options,
  payload.sort_order,
  false,
  false,
  payload.correct_answer,
  payload.explanation
from new_event
cross join (
  values
    (
      'Among adults age 50 and older, how many have used AI in some form?',
      '["About 1 in 3 (33%)", "More than half (55%)", "About 3 in 4 (77%)"]'::jsonb,
      0,
      'More than half (55%)',
      'In a survey of nearly 3,000 Americans over 50, 55% reported using some type of AI technology — either a voice assistant like Alexa, or a text chatbot like ChatGPT.'
    ),
    (
      'Among older adults who use AI — which type do they use more?',
      '["Text chatbots like ChatGPT — twice as popular", "Voice assistants like Alexa — twice as popular", "About equal — people use both the same amount"]'::jsonb,
      1,
      'Voice assistants like Alexa — twice as popular',
      '50% used a voice assistant in the past year. Only 25% used a text chatbot — half as many. Talking to technology feels natural. Typing to it is still a newer habit for many.'
    ),
    (
      'Of older adults using AI-powered home security cameras and doorbells, how many said they felt safer?',
      '["About 3 in 4 (72%)", "About 5 in 6 (84%)", "Nearly all of them (96%)"]'::jsonb,
      2,
      'Nearly all of them (96%)',
      'Of older adults using AI-powered home security, a remarkable 96% said they felt safer — one of the highest satisfaction rates in the entire study. When AI is practical and tangible, people embrace it quickly.'
    ),
    (
      'When asked whether they trust AI-generated content, what did older adults say?',
      '["Most trust it — about 3 in 4 said yes", "They''re split roughly down the middle", "Most don''t — fewer than 1 in 3 said yes"]'::jsonb,
      3,
      'They''re split roughly down the middle',
      '54% said they trust AI-generated content. 46% said they do not. And only half felt confident they could spot when AI content was wrong. And it''s getting more difficult to tell every day.'
    ),
    (
      'What share of older adults said they want to know when content was made by AI?',
      '["About 6 in 10 (60%)", "About 3 in 4 (75%)", "9 in 10 (90%)"]'::jsonb,
      4,
      '9 in 10 (90%)',
      '9 in 10 older adults want to know when content was generated by AI. On top of that, nearly 80% said they want to learn more about AI risks — where it can go wrong and what to do about it. Another good use of AI tools — to detect other AI tools!'
    )
) as payload(prompt, options, sort_order, correct_answer, explanation);

commit;

-- URLs:
-- Vote:     https://scambomb.com/poll/event/TRIVIA
-- Results:  https://scambomb.com/poll/event/TRIVIA/results
-- Control:  https://scambomb.com/poll/event/TRIVIA/control
